using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BlogPost.Core.Enums
{
    public enum WebDevelopmentSkill
    {
        HTML,
        CSS,
        JavaScript,
        TypeScript,
        ReactJS,
        Angular,
        VueJS,
        Bootstrap,
        ResponsiveDesign,
        WebAccessibility,
        Sass,
        Less,
        CSSFrameworks,
        FrontEndTesting,
        WebPerformanceOptimization,
        WebPack,
        Babel,
        GraphQL,
        RESTAPIs,
        JSON,
        AJAX,
        HTTP,
        WebSockets,
        ProgressiveWebApps,
        FrontEndBuildTools,
        WebSecurity,
        CrossBrowserCompatibility,
        UIUXDesign,
        FrontEndFrameworks,
        CMSIntegration,
        VersionControl,
        CommandLine,
        NodeJS,
        ExpressJS,
        ASPNETCore,
        RubyonRails,
        PythonDjango,
        PHP,
        Laravel,
        Ruby,
        BackEndDatabases,
        SQL,
        NoSQL,
        ServerManagement,
        CloudServices,
        DevOps,
        ContinuousIntegration,
        RESTfulAPIs,
        AuthenticationAuthorization,
        APIAuthentication,
        UnitTesting,
        IntegrationTesting,
        EndtoEndTesting,
        RealTimeApplications,
        OWASPTop10,
        CrossSiteScripting,
        CrossSiteRequestForgery,
        SQLInjection,
        ContentSecurityPolicy,
        HTTPS,
        WebVulnerabilityScanning,
        WebAnalytics,
        SEO,
        GoogleAnalytics,
        PerformanceOptimization,
        WebsiteMonitoring,
        TroubleshootingDebugging,
        ProblemSolving,
        CommunicationSkills,
        ProjectManagement,
        AgileScrum,
        Kanban,
        TechnicalDocumentation,
        ClientCommunication,
        TeamCollaboration,
        ContinuousLearning,
        TimeManagement
    }

}
